### ISSUE TITLE
What's the differences between absolute coordinate label and heatmaps label

### ISSUE THREAD

**Issue by jxlijunhao** [YuliangXiu/MobilePose-pytorch#1]
Hi, 
   thanks for sharing your repo. And There is a question that confused me a lot, What's the differences between absolute coordinate label and heatmaps label in training process, and which method will generate robust prediction ? I saw many papers transfer the coordinate to heatmaps

**Comment by YuliangXiu** [comment]
The reason why I transfer heatmap to coordinate is because we want to achieve faster inference speed. The heatmap based methods need to do peak extraction on final generated heatmaps, which will harm inference speed. While coordinate regression can directly get final (x,y) coordinates. 

But coord regression methods are not capable to beat heatmap based methods in accuracy, this is why so many methods transfer to heatmaps, so if you want to generate robust prediction, I think heatmap is a better choice.
